Rewrite cleanup

diff --git a/scripts/install-dm-stack b/scripts/install-dm-stack
--- a/scripts/install-dm-stack
+++ b/scripts/install-dm-stack
@@ -26,15 +26,44 @@ source $stackdir/loadLSST.bash
 for prod in $EUPS_PRODUCTS; do
     eups distrib install --no-server-tags "$prod" -t "$EUPS_TAG"
 done
-find ${stackdir} -exec strip --strip-unneeded --preserve-dates {} + \
-     > /dev/null 2>&1 || true
-find ${stackdir} -maxdepth 5 -name tests -type d -exec rm -rf {} + \
-       > /dev/null 2>&1 || true
-find ${stackdir} -maxdepth 6 \
-       \( -path "*doc/html" -o -path "*doc/xml" \) -type d -exec rm -rf {} + \
-       > /dev/null 2>&1 || true
-find ${stackdir} -maxdepth 5 -name src -type d -exec rm -rf {} + \
-       > /dev/null 2>&1 || true
+
+# Let's hope there are no spaces in filenames under $EUPS_PATH
+echo "---cleanup---"
+echo "Pre-cleanup ${stackdir} size:"
+du -sm ${stackdir}
+echo "ALL THE THINGS"
+find ${EUPS_PATH} -print
+echo "DONE WITH ALL THE THINGS"
+for dirn in tests src .git; do
+    victims=$(find ${EUPS_PATH} -name ${dirn} -type d -print)
+    echo "'${dirn}' dirs to delete:"
+    echo "${victims}"
+    if [ -n "${victims}" ]; then
+	rm -rf ${victims}
+    fi
+done
+victims=$(find ${EUPS_PATH} \
+	       \( -path "*doc/html" -o -path "*doc/xml" \) \
+	  -type d -print)
+echo "doc dirs to delete:"
+echo "${victims}"
+rm -rf ${victims}
+echo "Pre-strip ${stackdir} size"
+du -sm
+# Do this the hard way
+libs=$(find ${EUPS_PATH} -type f -name "*.so" -print)
+echo "Libraries to strip: ${libs}"
+for l in ${libs}; do
+    strip -p --strip-unneeded "${l}" || echo "Strip failed"
+done
+exes=$(find ${EUPS_PATH} -type f -executable -print)
+echo "Executables to strip: ${exes}"
+for e in ${exes}; do
+    strip -p --strip-unneeded "${e}" || echo "Strip failed"
+done
+echo "Post-cleanup ${stackdir} size:"
+du -sm ${stackdir}
+echo "---end cleanup---"
 
 for product in lsst_distrib lsst_sitcom; do
     eups distrib install -t $TAG $product
